/**
 * OPAL Connector - Comprehensive Type Definitions
 *
 * This file contains all TypeScript interfaces and type definitions for the
 * Optimizely Opal integration using osa_workflow_data.
 *
 * Supports all 9 OPAL agents with structured data validation.
 */

// ============================================================================
// CORE AGENT TYPES
// ============================================================================

/**
 * Valid OPAL Agent IDs - Enum for type safety
 */
export type OPALAgentId =
  | 'content_review'
  | 'geo_audit'
  | 'audience_suggester'
  | 'experiment_blueprinter'
  | 'personalization_idea_generator'
  | 'roadmap_generator'
  | 'integration_health'
  | 'cmp_organizer'
  | 'customer_journey';

/**
 * Agent execution status during workflow
 */
export type AgentExecutionStatus =
  | 'pending'     // Agent queued but not started
  | 'running'     // Agent currently executing
  | 'completed'   // Agent finished successfully
  | 'failed'      // Agent failed with error
  | 'timeout'     // Agent exceeded time limit
  | 'cancelled';  // Agent execution was cancelled

// ============================================================================
// OSA WORKFLOW DATA STRUCTURES
// ============================================================================

/**
 * Core metadata for every agent execution
 */
export interface AgentExecutionMetadata {
  /** Agent execution time in milliseconds */
  execution_time_ms: number;

  /** ISO timestamp when agent completed execution */
  timestamp: string;

  /** Whether the agent executed successfully */
  success: boolean;

  /** Error details if agent execution failed */
  error_message?: string;

  /** Agent execution start time */
  started_at?: string;

  /** Agent execution completion time */
  completed_at?: string;

  /** Progress percentage (0-100) if agent supports progress reporting */
  progress_percentage?: number;

  /** Number of retry attempts made */
  retry_count?: number;

  /** Additional agent-specific metadata */
  [key: string]: any;
}

/**
 * Base structure for all agent execution results
 */
export interface BaseAgentExecutionResult {
  /** Analysis summary generated by the agent */
  summary: string;

  /** Key recommendations from the agent */
  recommendations: string[];

  /** Confidence score (0-1) in the analysis quality */
  confidence_score: number;

  /** Data points analyzed by the agent */
  data_points_analyzed: number;

  /** Agent-specific insights and findings */
  insights: Record<string, any>;

  /** URLs or references used in analysis */
  references?: string[];

  /** Tags for categorizing the analysis */
  tags?: string[];
}

// ============================================================================
// AGENT-SPECIFIC EXECUTION RESULTS
// ============================================================================

/**
 * Content Review Agent - Analyzes content quality and optimization
 */
export interface ContentReviewExecutionResult extends BaseAgentExecutionResult {
  content_quality_score: number; // 0-100
  seo_optimization_score: number; // 0-100
  readability_score: number; // 0-100
  content_gaps: string[];
  optimization_opportunities: {
    type: 'seo' | 'readability' | 'engagement' | 'conversion';
    description: string;
    impact: 'low' | 'medium' | 'high';
  }[];
  keyword_analysis: {
    target_keywords: string[];
    keyword_density: number;
    competitor_keywords: string[];
  };
}

/**
 * Geographic Audit Agent - Evaluates geographic performance
 */
export interface GeoAuditExecutionResult extends BaseAgentExecutionResult {
  geographic_performance: {
    region: string;
    performance_score: number; // 0-100
    conversion_rate: number;
    traffic_volume: number;
  }[];
  underperforming_regions: string[];
  growth_opportunities: {
    region: string;
    potential_uplift: number; // percentage
    recommended_actions: string[];
  }[];
  regional_preferences: Record<string, any>;
}

/**
 * Audience Suggester Agent - Analyzes and recommends audience segments
 */
export interface AudienceSuggesterExecutionResult extends BaseAgentExecutionResult {
  audience_segments: {
    segment_name: string;
    size_estimate: number;
    characteristics: Record<string, any>;
    conversion_potential: number; // 0-100
    targeting_criteria: Record<string, any>;
  }[];
  lookalike_opportunities: {
    source_segment: string;
    similarity_score: number; // 0-1
    estimated_reach: number;
  }[];
  behavioral_patterns: Record<string, any>;
  demographic_insights: Record<string, any>;
}

/**
 * Experiment Blueprinter Agent - Creates A/B test and experiment strategies
 */
export interface ExperimentBlueprintersExecutionResult extends BaseAgentExecutionResult {
  experiment_proposals: {
    experiment_name: string;
    hypothesis: string;
    success_metrics: string[];
    variations: {
      name: string;
      description: string;
      implementation_details: string;
    }[];
    estimated_duration_days: number;
    sample_size_required: number;
    expected_lift: number; // percentage
    confidence_level: number; // 0-1
  }[];
  testing_roadmap: {
    quarter: string;
    experiments: string[];
    dependencies: string[];
  }[];
  statistical_power_analysis: Record<string, any>;
}

/**
 * Personalization Idea Generator Agent - Generates personalization strategies
 */
export interface PersonalizationIdeaGeneratorExecutionResult extends BaseAgentExecutionResult {
  personalization_strategies: {
    strategy_name: string;
    target_segments: string[];
    personalization_type: 'content' | 'layout' | 'offers' | 'timing' | 'journey';
    implementation_complexity: 'low' | 'medium' | 'high';
    expected_impact: number; // 0-100
    implementation_details: string;
  }[];
  content_variations: {
    element_type: string;
    variations: Record<string, string>;
    targeting_rules: Record<string, any>;
  }[];
  journey_optimizations: Record<string, any>;
  real_time_triggers: string[];
}

/**
 * Roadmap Generator Agent - Creates implementation roadmaps and timelines
 */
export interface RoadmapGeneratorExecutionResult extends BaseAgentExecutionResult {
  implementation_phases: {
    phase_name: string;
    duration_weeks: number;
    deliverables: string[];
    dependencies: string[];
    resources_required: {
      developers: number;
      designers: number;
      data_analysts: number;
      other: Record<string, number>;
    };
    success_criteria: string[];
  }[];
  timeline_milestones: {
    milestone_name: string;
    target_date: string;
    deliverables: string[];
    stakeholders: string[];
  }[];
  risk_assessment: {
    risk_category: string;
    probability: 'low' | 'medium' | 'high';
    impact: 'low' | 'medium' | 'high';
    mitigation_strategy: string;
  }[];
  resource_allocation: Record<string, any>;
}

/**
 * Integration Health Agent - Monitors DXP integration status
 */
export interface IntegrationHealthExecutionResult extends BaseAgentExecutionResult {
  integration_status: {
    service_name: string;
    status: 'healthy' | 'warning' | 'critical' | 'down';
    response_time_ms: number;
    uptime_percentage: number;
    last_check: string;
    error_rate: number; // 0-1
  }[];
  performance_metrics: {
    api_latency_ms: number;
    throughput_rps: number; // requests per second
    error_count_24h: number;
    data_sync_status: 'synced' | 'pending' | 'error';
  };
  health_recommendations: {
    priority: 'low' | 'medium' | 'high' | 'critical';
    category: 'performance' | 'reliability' | 'security' | 'data_quality';
    recommendation: string;
    estimated_effort: 'hours' | 'days' | 'weeks';
  }[];
  integration_dependencies: Record<string, any>;
}

/**
 * CMP Organizer Agent - Organizes campaign management workflows
 */
export interface CMPOrganizerExecutionResult extends BaseAgentExecutionResult {
  campaign_workflows: {
    workflow_name: string;
    automation_level: number; // 0-100 percentage
    efficiency_score: number; // 0-100
    bottlenecks: string[];
    optimization_suggestions: string[];
  }[];
  process_improvements: {
    current_process: string;
    improved_process: string;
    time_savings_hours: number;
    effort_reduction_percentage: number;
  }[];
  automation_opportunities: {
    task_name: string;
    current_manual_effort_hours: number;
    automation_complexity: 'low' | 'medium' | 'high';
    roi_estimate: number; // return on investment
  }[];
  workflow_dependencies: Record<string, any>;
}

/**
 * Customer Journey Agent - Maps journey touchpoints and optimization opportunities
 */
export interface CustomerJourneyExecutionResult extends BaseAgentExecutionResult {
  journey_stages: {
    stage_name: string;
    touchpoints: string[];
    conversion_rate: number; // 0-1
    drop_off_rate: number; // 0-1
    optimization_score: number; // 0-100
    pain_points: string[];
    opportunities: string[];
  }[];
  cross_channel_insights: {
    channel_combination: string[];
    performance_score: number; // 0-100
    user_preference: number; // 0-1
    attribution_weight: number; // 0-1
  }[];
  journey_optimizations: {
    stage: string;
    optimization_type: 'content' | 'timing' | 'channel' | 'experience';
    description: string;
    expected_impact: number; // percentage improvement
    implementation_effort: 'low' | 'medium' | 'high';
  }[];
  behavioral_flows: Record<string, any>;
  retention_insights: Record<string, any>;
}

// ============================================================================
// OSA WORKFLOW DATA PAYLOAD STRUCTURE
// ============================================================================

/**
 * Individual agent data within an OSA workflow
 */
export interface OSAAgentData {
  /** Unique identifier for the agent */
  agent_id: OPALAgentId;

  /** Human-readable name of the agent */
  agent_name: string;

  /** Workflow identifier for data correlation */
  workflow_id: string;

  /** Agent-specific execution results and analysis data */
  execution_results: BaseAgentExecutionResult |
    ContentReviewExecutionResult |
    GeoAuditExecutionResult |
    AudienceSuggesterExecutionResult |
    ExperimentBlueprintersExecutionResult |
    PersonalizationIdeaGeneratorExecutionResult |
    RoadmapGeneratorExecutionResult |
    IntegrationHealthExecutionResult |
    CMPOrganizerExecutionResult |
    CustomerJourneyExecutionResult;

  /** Execution metadata and performance metrics */
  metadata: AgentExecutionMetadata;

  /** Additional agent output data (flexible structure) */
  output_data?: Record<string, any>;
}

/**
 * Complete OSA workflow data payload from OPAL
 */
export interface OSAWorkflowParameters {
  /** Unique identifier for the OPAL workflow execution */
  workflow_id: string;

  /** Array of agent execution results and output data */
  agent_data: OSAAgentData[];

  /** Name of the client organization for context (optional) */
  client_name?: string;

  /** List of business objectives to guide analysis (optional) */
  business_objectives?: string[];

  /** Workflow execution timestamp */
  workflow_timestamp?: string;

  /** Total workflow execution time */
  workflow_execution_time_ms?: number;

  /** Workflow metadata */
  workflow_metadata?: Record<string, any>;
}

// ============================================================================
// OSA WORKFLOW RESPONSE STRUCTURE
// ============================================================================

/**
 * Response structure for OSA workflow data processing
 */
export interface OSAWorkflowResult {
  /** Workflow identifier confirmation */
  workflow_id: string;

  /** Processing status */
  status: 'received' | 'processing' | 'completed' | 'failed';

  /** List of agent IDs successfully received and processed */
  agents_received: OPALAgentId[];

  /** Total number of agents processed */
  total_agents: number;

  /** Human-readable status message */
  message: string;

  /** ISO timestamp of processing completion */
  timestamp: string;

  /** Processing performance metrics */
  processing_time_ms?: number;

  /** Any errors encountered during processing */
  errors?: {
    agent_id: OPALAgentId;
    error_message: string;
    error_code?: string;
  }[];

  /** Additional response metadata */
  metadata?: Record<string, any>;
}

// ============================================================================
// VALIDATION AND UTILITY TYPES
// ============================================================================

/**
 * Configuration for each OPAL agent
 */
export interface OPALAgentConfig {
  /** Human-readable agent name */
  name: string;

  /** Agent description and purpose */
  description: string;

  /** Estimated execution time in milliseconds */
  estimated_runtime_ms: number;

  /** Timeout threshold in milliseconds */
  timeout_threshold_ms: number;

  /** Agent category for organization */
  category: 'analysis' | 'optimization' | 'strategy' | 'monitoring';

  /** Expected output data structure validation schema */
  output_schema?: Record<string, any>;
}

/**
 * Agent validation result
 */
export interface AgentValidationResult {
  /** Whether the agent data is valid */
  is_valid: boolean;

  /** Validation errors if any */
  errors: string[];

  /** Validation warnings if any */
  warnings: string[];

  /** Validated agent data (if valid) */
  validated_data?: OSAAgentData;
}

/**
 * Workflow validation result
 */
export interface WorkflowValidationResult {
  /** Whether the entire workflow is valid */
  is_valid: boolean;

  /** Overall validation errors */
  errors: string[];

  /** Overall validation warnings */
  warnings: string[];

  /** Agent-specific validation results */
  agent_results: Record<OPALAgentId, AgentValidationResult>;

  /** Validated workflow data (if valid) */
  validated_data?: OSAWorkflowParameters;
}

// ============================================================================
// EXPORT ALL TYPES
// ============================================================================

export type {
  // Core types
  OPALAgentId,
  AgentExecutionStatus,
  AgentExecutionMetadata,
  BaseAgentExecutionResult,

  // Agent-specific results
  ContentReviewExecutionResult,
  GeoAuditExecutionResult,
  AudienceSuggesterExecutionResult,
  ExperimentBlueprintersExecutionResult,
  PersonalizationIdeaGeneratorExecutionResult,
  RoadmapGeneratorExecutionResult,
  IntegrationHealthExecutionResult,
  CMPOrganizerExecutionResult,
  CustomerJourneyExecutionResult,

  // Workflow types
  OSAAgentData,
  OSAWorkflowParameters,
  OSAWorkflowResult,

  // Validation types
  OPALAgentConfig,
  AgentValidationResult,
  WorkflowValidationResult
};