#!/bin/bash

# OPAL/OSA Local Development Setup Script
# Phase 0: Setup & Safety for Next.js + Node.js environment

set -e  # Exit on error

echo "🚀 OPAL/OSA Local Development Setup"
echo "=================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Helper functions
log_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

log_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

log_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Check Node.js version
check_node_version() {
    log_info "Checking Node.js version..."

    if ! command -v node &> /dev/null; then
        log_error "Node.js is not installed. Please install Node.js 18+ from https://nodejs.org/"
        exit 1
    fi

    NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)

    if [ "$NODE_VERSION" -lt 18 ]; then
        log_error "Node.js version $NODE_VERSION detected. Please upgrade to Node.js 18 or higher."
        exit 1
    fi

    log_success "Node.js version $(node -v) is compatible (18+ required)"
}

# Setup file-based fallback configuration
setup_file_fallback() {
    log_info "Setting up file-based fallback configuration..."

    # Create data directory for file-based storage
    mkdir -p data/local
    mkdir -p data/cache
    mkdir -p data/logs

    # Create basic JSON files for local development
    if [ ! -f "data/local/workflows.json" ]; then
        echo '[]' > data/local/workflows.json
        log_success "Created local workflows.json file"
    fi

    if [ ! -f "data/local/webhook-events.json" ]; then
        echo '[]' > data/local/webhook-events.json
        log_success "Created local webhook-events.json file"
    fi

    if [ ! -f "data/local/performance-metrics.json" ]; then
        echo '[]' > data/local/performance-metrics.json
        log_success "Created local performance-metrics.json file"
    fi

    log_success "File-based fallback storage configured"
}

# Configure environment variables for dev mode
setup_dev_environment() {
    log_info "Configuring development environment variables..."

    # Backup existing .env.local if it exists
    if [ -f ".env.local" ]; then
        BACKUP_FILE=".env.local.backup.$(date +%Y%m%d-%H%M%S)"
        cp .env.local "$BACKUP_FILE"
        log_warning "Backed up existing .env.local to $BACKUP_FILE"
    fi

    # Create development .env.local file
    cat > .env.local << 'EOF'
# OPAL/OSA Local Development Configuration
# Generated by setup-local-dev.sh

# Environment
NODE_ENV=development
BASE_URL=http://localhost:3000

# File-based fallback (no Supabase required)
USE_FILE_STORAGE=true
FILE_STORAGE_PATH=./data/local

# OPAL Configuration (Development)
OPAL_API_BASE=https://api.opal.optimizely.com
OPAL_WORKSPACE_ID=dev-workspace-placeholder
OPAL_API_KEY=dev-api-key-placeholder

# Webhook Configuration (Development)
OPAL_WEBHOOK_URL=http://localhost:3000/api/webhooks/opal-workflow
OPAL_WEBHOOK_AUTH_KEY=dev-webhook-auth-key-32-chars-minimum
OSA_WEBHOOK_SHARED_SECRET=dev-webhook-secret-32-chars-minimum

# Security (Development - not for production)
OPAL_STRATEGY_WORKFLOW_AUTH_KEY=dev-strategy-workflow-key-32-chars
JWT_SECRET=dev-jwt-secret-key-32-chars-minimum

# Debug Configuration
DEBUG=true
OPAL_DEBUG_MODE=true
LOG_LEVEL=debug

# Development Features
ENABLE_DEV_TOOLS=true
ENABLE_API_DOCS=true
ENABLE_DEBUG_ENDPOINTS=true

# Supabase (Optional - will fallback to file storage if not configured)
# SUPABASE_URL=your-supabase-url
# SUPABASE_ANON_KEY=your-supabase-anon-key

# External Services (Optional for development)
# SENDGRID_API_KEY=optional-for-dev
# GOOGLE_ANALYTICS_PROPERTY_ID=optional-for-dev
EOF

    log_success "Created development .env.local configuration"
}

# Clean previous builds and locks
clean_environment() {
    log_info "Cleaning previous builds and locks..."

    # Remove Next.js build artifacts
    rm -rf .next
    rm -rf node_modules/.cache

    # Remove any lingering lock files
    rm -f .next/dev/lock 2>/dev/null || true

    log_success "Environment cleaned"
}

# Install dependencies
install_dependencies() {
    log_info "Installing dependencies..."

    if [ ! -d "node_modules" ]; then
        npm install
        log_success "Dependencies installed"
    else
        log_info "Dependencies already installed, running npm ci for clean install..."
        npm ci
        log_success "Dependencies updated"
    fi
}

# Validate health endpoint
validate_health() {
    log_info "Starting development server for validation..."

    # Start dev server in background
    npm run dev &
    DEV_PID=$!

    # Wait for server to start
    log_info "Waiting for server to start..."
    sleep 5

    # Test health endpoint
    for i in {1..10}; do
        if curl -s http://localhost:3000/api/opal/health > /dev/null 2>&1; then
            log_success "Health endpoint is responsive at http://localhost:3000/api/opal/health"
            break
        elif curl -s http://localhost:3001/api/opal/health > /dev/null 2>&1; then
            log_success "Health endpoint is responsive at http://localhost:3001/api/opal/health"
            break
        else
            log_info "Waiting for server... (attempt $i/10)"
            sleep 2
        fi
    done

    # Stop the dev server
    kill $DEV_PID 2>/dev/null || true
    sleep 2
}

# Create development instructions
create_instructions() {
    log_info "Creating development instructions..."

    cat > DEVELOPMENT_SETUP.md << 'EOF'
# OPAL/OSA Local Development Setup

## Prerequisites
- ✅ Node.js 18+ (Current: `node --version`)
- ✅ npm (Current: `npm --version`)

## Quick Start

### 1. Install Dependencies
```bash
npm install
```

### 2. Start Development Server
```bash
npm run dev
```

### 3. Validate Health
Visit: http://localhost:3000/api/opal/health

## Development Features Enabled

### File-based Fallback
- 🗂️ Local JSON storage in `./data/local/`
- 🔄 No Supabase account required
- 📊 Performance metrics stored locally

### Debug Tools
- 🐛 Debug mode enabled (`DEBUG=true`)
- 📝 Detailed logging (`LOG_LEVEL=debug`)
- 🔍 Development API endpoints available

### Available Scripts
```bash
# Development
npm run dev              # Start development server
npm run build           # Build for production (local only)

# Testing
npm run test            # Run unit tests
npm run test:watch      # Run tests in watch mode
npm run test:integration # Run integration tests

# Validation
npm run validate:opal   # Validate OPAL integration
npm run validate:security # Run security checks
npm run error-check     # Check for common errors

# OPAL Tools
npm run start:opal-tools # Start OPAL SDK tools
```

### Key Endpoints
- Health: http://localhost:3000/api/opal/health
- Discovery: http://localhost:3000/api/opal/discovery
- Webhook: http://localhost:3000/api/webhooks/opal-workflow
- Debug: http://localhost:3000/api/debug/env (dev only)

## Safety Notes
- 🚫 **NO PRODUCTION DEPLOYMENT** - This is development only
- 🔒 Development credentials are safe for local use only
- 📁 File-based storage keeps everything local
- 🧪 Safe to experiment and test

## Troubleshooting

### Port Issues
If port 3000 is busy, Next.js will use 3001:
```bash
# Kill processes on common ports
lsof -ti:3000,3001 | xargs kill
npm run dev
```

### File Storage Issues
```bash
# Reset local storage
rm -rf data/local
mkdir -p data/local
echo '[]' > data/local/workflows.json
```

### Environment Issues
```bash
# Regenerate development environment
./scripts/setup-local-dev.sh
```
EOF

    log_success "Created DEVELOPMENT_SETUP.md instructions"
}

# Main setup process
main() {
    echo ""
    log_info "Starting OPAL/OSA local development setup..."
    echo ""

    check_node_version
    clean_environment
    setup_file_fallback
    setup_dev_environment
    install_dependencies
    create_instructions

    echo ""
    log_success "🎉 Local development environment setup complete!"
    echo ""
    echo "Next steps:"
    echo "1. Run: npm run dev"
    echo "2. Visit: http://localhost:3000/api/opal/health"
    echo "3. Read: ./DEVELOPMENT_SETUP.md for full instructions"
    echo ""
    log_warning "Remember: This is for LOCAL DEVELOPMENT ONLY - DO NOT deploy to production!"
    echo ""
}

# Run setup if script is executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi